services:
  private-qrcode-dev:
    image: private-qrcode-dev
    container_name: private-qrcode-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /private-qrcode
    ports:
      - "9229:9229"
      - "4200:4200"
    volumes:
      - ..:/private-qrcode:cached
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
